# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py
git:
  depth: 20

language: python
python:
  - 3.6
  - 3.7-dev

matrix:
  allow_failures:
    - python: 3.7-dev

install:
  - pip install --upgrade setuptools pip
  - python setup.py build bdist_wheel
  - pip install -e .[test]

script:
  ## Test if `pip install .[test]` installs all deps.
  - pytest -v

  ## Re-test EXACT deps on WHEEL, with COVERAGE.
  #
  - pip install -q -r requirements.txt -r requirements_dev.txt
  - pip uninstall polyvers -y
  - pip install -q dist/*.whl
  - pytest -q --cov=polyvers --cov-report=term-missing

after_success:
  - pip install python-coveralls
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then coveralls; fi
  - flake8 --show-source
