# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py
git:
  depth: 20

language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev

# matrix:
#   allow_failures:
#     - python: 3.7-dev

install:
  - pip install --upgrade setuptools pip

  - pip install -e ./pvlib[test]
  - python pvlib/setup.py build bdist_wheel

  - |
    if [ $TRAVIS_PYTHON_VERSION \> '3.5' ]; then
        pip install -e .[test]
        python setup.py build bdist_wheel
    fi

script:
  ## Check *polyversion* lib in older Pythons.
  - pytest -v pvlib

  ## Check *polyvers* cmd in newer python only.
  #
  - |
    if [ $TRAVIS_PYTHON_VERSION \> '3.5' ]; then
        pytest -v pvcmd
    fi

  ## Re-test EXACT deps on WHEEL, with COVERAGE.
  #
  - |
    if [ $TRAVIS_PYTHON_VERSION \> '3.5' ]; then
        pip install -q -r requirements.txt -r requirements_dev.txt
        pip uninstall polyvers -y
        pip install -q dist/*.whl
    fi

  - |
    if [ $TRAVIS_PYTHON_VERSION \> '3.5' ]; then
        pytest -q --cov=polyvers --cov-report=term-missing
    fi

  - |
    if [ $TRAVIS_PYTHON_VERSION \> '3.5' ]; then
        flake8 --show-source
    fi

  - |
    if [ $TRAVIS_PYTHON_VERSION \> '3.5' ]; then
        mypy \
            pvcmd/polyvers/vermath.py \
            pvcmd/polyvers/cmdlet/cmdlets.py \
            pvcmd/polyvers/cmdlet/errlog.py \
            pvcmd/polyvers/pvproject.py \
            pvcmd/polyvers/engrave.py \
            pvcmd/polyvers/pvtags.py \
            pvcmd/polyvers/cli.py \
            pvcmd/polyvers/bumpcmd.py
    fi

after_success:
  - pip install python-coveralls
  - if [ $TRAVIS_PYTHON_VERSION \> '3.5' ]; then coveralls; fi
