# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - 3.6
  - 3.7-dev

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# command to run tests, e.g. python setup.py test
script:
  - pip install .[test]
  - python setup.py build bdist_wheel
  - tox


matrix:
  allow_failures:
    - python: 3.7-dev
