## TIP: multiLines in Appveoyr:
#  https://stackoverflow.com/questions/37627248/how-to-split-a-command-over
#
build: false
version: '0.0.0+build.{build}'
clone_depth: 20
environment:
  GIT_PATH:   "C:\\Program Files\\Git\\mingw64\\libexec\\git-core"

  matrix:
   - PYTHON: "C:\\Python36-x64"
     PYTHON_VERSION: "3.6"
     PYTHON_ARCH: "64"
   - PYTHON: "C:\\Python35-x64"
     PYTHON_VERSION: "3.5"
     PYTHON_ARCH: "64"
   - PYTHON: "C:\\Python34-x64"
     PYTHON_VERSION: "3.4"
     PYTHON_ARCH: "64"
   - PYTHON: "C:\\Python27-x64"
     PYTHON_VERSION: "2.7"
     PYTHON_ARCH: "64"

init:
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%GIT_PATH%;%PATH%
  - ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
  - ECHO %PATH%
  - python --version

install:
  - python -m pip install --upgrade setuptools pip wheel

test_script:
  - pip install -q -r requirements_dev.txt
  - IF "%PYTHON_VERSION%" == "3.6" (
      pip install -q -r requirements.txt
    )

  ## Build and smoketest WHEELs
  #
  # Only $CWD/setup.cfg is read
  - sed -i 's/skip_polyversion_check = false/skip_polyversion_check = true/' setup.cfg
  - python pvlib/setup.py build bdist_wheel

  - IF "%PYTHON_VERSION%" == "3.6" (
        python setup.py build bdist_wheel
    )

  ## Install sources and PYTEST both pvlib & pvcmd.
  #
  - pip install -e pvlib && pytest -v pvlib
  - python pvlib/setup.py build bdist_wheel &&
  - IF "%PYTHON_VERSION%" == "3.6" (
        python pvlib/setup.py build bdist_wheel &&
        pip install -e pvlib  && pytest -v pvcmd
    )

