{% set name = "polyversion" %}
{% set version = "0.2.2a1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/2d/d5/43e0b2311f96900a0c9fee0631a6441925ec7323bbc638b80d2c02553c30/polyversion-0.2.2a1.tar.gz
  sha256: 4f9fb8da12bfe0ac35ed5670a9193808da1e6c7fc7a610ff5b87d55ad365d3c1

build:
  number: 0
  noarch: python
  entry_points:
    - {{ name }} = {{ name }}.__main__:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  build:
    - setuptools
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - polyversion
  commands:
    - polyversion --help
    - pytest
    - > 
      mypy 
      pvcmd/polyvers/vermath.py
      pvcmd/polyvers/cmdlet/cmdlets.py
      pvcmd/polyvers/cmdlet/errlog.py
      pvcmd/polyvers/pvproject.py
      pvcmd/polyvers/engrave.py
      pvcmd/polyvers/pvtags.py
      pvcmd/polyvers/cli.py
      pvcmd/polyvers/bumpcmd.py
  requires:
    - flake8
    - flake8-builtins
    - flake8-mutable
    - mypy
    - pytest
    - pytest-runner
    - pytest-cov

about:
  home: https://github.com/ankostis/polyvers
  license: MIT
  license_family: MIT
  license_file: ../../../LICENSE.txt
  summary: Polyvers's lib to derive subproject versions from tags on Git monorepos.

  doc_url:  https://polyvers.readthedocs.org/
  dev_url:  https://github.com/{{ name }}/{{ name }}

extra:
  recipe-maintainers:
    - ankostis
  copy_test_source_files: false
